###### CREATE A WEB APPLICATION WHICH ACCEPTS A MOVIE NAME FROM THE USER AND DISPLAYS FIVE SIMILAR MOVIES TO THE USER.

In [1]:
import pandas as pd
import numpy as np

In [2]:
credits=pd.read_csv("credits.csv")
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [3]:
movies=pd.read_csv("movies.csv")
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [7]:
movies['production_companies']

0       [{"name": "Ingenious Film Partners", "id": 289...
1       [{"name": "Walt Disney Pictures", "id": 2}, {"...
2       [{"name": "Columbia Pictures", "id": 5}, {"nam...
3       [{"name": "Legendary Pictures", "id": 923}, {"...
4             [{"name": "Walt Disney Pictures", "id": 2}]
                              ...
4816             [{"name": "Columbia Pictures", "id": 5}]
4817                                                   []
4818    [{"name": "Front Street Pictures", "id": 3958}...
4819                                                   []
4820    [{"name": "rusty bear entertainment", "id": 87...
Name: production_companies, Length: 4821, dtype: object

In [4]:
movies=movies.merge(credits,on='title')
movies.shape

(4809, 23)

In [6]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [5]:
movies['original_language'].value_counts()

en    4510
fr      70
es      32
zh      27
de      27
hi      19
ja      16
it      14
ko      12
cn      12
ru      11
pt       9
da       7
sv       5
nl       4
fa       4
th       3
he       3
ta       2
cs       2
ro       2
id       2
ar       2
vi       1
sl       1
ps       1
no       1
ky       1
hu       1
pl       1
af       1
nb       1
tr       1
is       1
xx       1
te       1
el       1
Name: original_language, dtype: int64

In [8]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 901.7+ KB

In [9]:
#distribution of original_language is not uniform so skip it.
#useful fields
#genres,id,keywords,title,overview,cast,crew

In [5]:
movies=movies[['genres','movie_id','keywords','title','overview','cast','crew']]

In [6]:
movies.head(3)

,genres,movie_id,keywords,title,overview,cast,crew
0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."

In [7]:
#missing data
movies.isnull().sum()

genres      0
movie_id    0
keywords    0
title       0
overview    3
cast        0
crew        0
dtype: int64

In [8]:
movies.dropna(inplace=True)

In [9]:
#duplicate data
movies.duplicated().sum()
#no duplicate rows

0

In [ ]:
#to create tags - join overview, cast crew.

In [18]:
movies['genres'][0]

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [ ]:
#here genres is a string so convert string of list to list. use module ast.

In [10]:
import ast

In [11]:
def convert(obj):
    l=[]
    for i in ast.literal_eval(obj):
        l.append(i['name'])
    return l

In [12]:
movies['genres']=movies['genres'].apply(convert)

In [10]:
movies.head(1)

,genres,id,keywords,title,overview,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [22]:
movies['keywords'][0]

'[{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "space war"}, {"id": 3388, "name": "space colony"}, {"id": 3679, "name": "society"}, {"id": 3801, "name": "space travel"}, {"id": 9685, "name": "futuristic"}, {"id": 9840, "name": "romance"}, {"id": 9882, "name": "space"}, {"id": 9951, "name": "alien"}, {"id": 10148, "name": "tribe"}, {"id": 10158, "name": "alien planet"}, {"id": 10987, "name": "cgi"}, {"id": 11399, "name": "marine"}, {"id": 13065, "name": "soldier"}, {"id": 14643, "name": "battle"}, {"id": 14720, "name": "love affair"}, {"id": 165431, "name": "anti war"}, {"id": 193554, "name": "power relations"}, {"id": 206690, "name": "mind and soul"}, {"id": 209714, "name": "3d"}]'

In [13]:
movies['keywords']=movies['keywords'].apply(convert)

In [12]:
movies['keywords'].head()

0    [culture clash, future, space war, space colon...
1    [ocean, drug abuse, exotic island, east india ...
2    [spy, based on novel, secret agent, sequel, mi...
3    [dc comics, crime fighter, terrorist, secret i...
4    [based on novel, mars, medallion, space travel...
Name: keywords, dtype: object

In [25]:
movies['cast'][0]

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [26]:
#pick only first three actors. pick first three 'name' from cast

In [14]:
def convert3(obj):
    l=[]
    c=0
    for i in ast.literal_eval(obj):
        if c!=3:
            l.append(i['name'])
            c+=1
        else:
            break
    return l

In [15]:
convert3(movies['cast'][1])

['Johnny Depp', 'Orlando Bloom', 'Keira Knightley']

In [16]:
movies['cast']=movies['cast'].apply(convert3)

In [28]:
movies.head()

,genres,id,keywords,title,overview,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[Action, Adventure, Crime]",206647,"[spy, based on novel, secret agent, sequel, mi...",Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[Action, Crime, Drama, Thriller]",49026,"[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[Action, Adventure, Science Fiction]",49529,"[based on novel, mars, medallion, space travel...",John Carter,"John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [ ]:
#pick director name from crew.
#pick the name where job isdirector

In [17]:
def fetch_director(obj):
    L=[]
    for i in ast.literal_eval(obj):
        if(i['job']=='Director'):
            L.append(i['name'])
            break
    return L

In [17]:
fetch_director(movies['crew'][0])

['James Cameron']

In [18]:
movies['crew']=movies['crew'].apply(fetch_director)

In [19]:
movies.head(3)

,genres,movie_id,keywords,title,overview,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,"[Action, Adventure, Crime]",206647,"[spy, based on novel, secret agent, sequel, mi...",Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes]

In [36]:
#convert overview from string to list

In [21]:
#example:
s="swetha is disciplined"
l=s.split()
l

['swetha', 'is', 'disciplined']

In [37]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [38]:
movies['overview'][0].split()

['In',
 'the',
 '22nd',
 'century,',
 'a',
 'paraplegic',
 'Marine',
 'is',
 'dispatched',
 'to',
 'the',
 'moon',
 'Pandora',
 'on',
 'a',
 'unique',
 'mission,',
 'but',
 'becomes',
 'torn',
 'between',
 'following',
 'orders',
 'and',
 'protecting',
 'an',
 'alien',
 'civilization.']

In [20]:
movies['overview']=movies['overview'].apply(lambda x : x.split())

In [25]:
movies.head(3)

,genres,movie_id,keywords,title,overview,cast,crew,tags
0,"[Action, Adventure, Fantasy, ScienceFiction]",19995,"[cultureclash, future, spacewar, spacecolony, ...",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,"[Adventure, Fantasy, Action]",285,"[ocean, drugabuse, exoticisland, eastindiatrad...",Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,"[Action, Adventure, Crime]",206647,"[spy, basedonnovel, secretagent, sequel, mi6, ...",Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes],"[A, cryptic, message, from, Bondâ€™s, past, send..."

In [34]:
#remove spaces between words of columns - keywords, cast ans crew.

In [22]:
movies.keywords[0]

['culture clash',
 'future',
 'space war',
 'space colony',
 'society',
 'space travel',
 'futuristic',
 'romance',
 'space',
 'alien',
 'tribe',
 'alien planet',
 'cgi',
 'marine',
 'soldier',
 'battle',
 'love affair',
 'anti war',
 'power relations',
 'mind and soul',
 '3d']

In [23]:
def removespace(obj):
    key=[]
    for i in obj:
        key.append(i.replace(" ",""))
    return key

In [21]:
movies["genres"].apply(removespace)

0       [Action, Adventure, Fantasy, ScienceFiction]
1                       [Adventure, Fantasy, Action]
2                         [Action, Adventure, Crime]
3                   [Action, Crime, Drama, Thriller]
4                [Action, Adventure, ScienceFiction]
                            ...
4804                       [Action, Crime, Thriller]
4805                               [Comedy, Romance]
4806               [Comedy, Drama, Romance, TVMovie]
4807                                              []
4808                                   [Documentary]
Name: genres, Length: 4806, dtype: object

In [ ]:
#Same functionality by using lambda function.

In [26]:
movies["genres"]=movies["genres"].apply(lambda x : [i.replace(" ","") for i in x] )

In [27]:
movies.head()

,genres,movie_id,keywords,title,overview,cast,crew,tags
0,"[Action, Adventure, Fantasy, ScienceFiction]",19995,"[cultureclash, future, spacewar, spacecolony, ...",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,"[Adventure, Fantasy, Action]",285,"[ocean, drugabuse, exoticisland, eastindiatrad...",Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,"[Action, Adventure, Crime]",206647,"[spy, basedonnovel, secretagent, sequel, mi6, ...",Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes],"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,"[Action, Crime, Drama, Thriller]",49026,"[dccomics, crimefighter, terrorist, secretiden...",The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,"[Action, Adventure, ScienceFiction]",49529,"[basedonnovel, mars, medallion, spacetravel, p...",John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [28]:
movies["keywords"]=movies["keywords"].apply(lambda x : [i.replace(" ","") for i in x] )
movies["cast"]=movies["cast"].apply(lambda x : [i.replace(" ","") for i in x] )
movies["crew"]=movies["crew"].apply(lambda x : [i.replace(" ","") for i in x] )

In [29]:
movies.head(3)

,genres,movie_id,keywords,title,overview,cast,crew,tags
0,"[Action, Adventure, Fantasy, ScienceFiction]",19995,"[cultureclash, future, spacewar, spacecolony, ...",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,"[Adventure, Fantasy, Action]",285,"[ocean, drugabuse, exoticisland, eastindiatrad...",Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,"[Action, Adventure, Crime]",206647,"[spy, basedonnovel, secretagent, sequel, mi6, ...",Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes],"[A, cryptic, message, from, Bondâ€™s, past, send..."

In [62]:
#Create tags columns by concatenating genres, keywords, overview, cast, crew.

In [30]:
movies["tags"]=movies["overview"] + movies["genres"] + movies["keywords"] + movies["cast"] + movies["crew"]

In [31]:
movies.head(3)

,genres,movie_id,keywords,title,overview,cast,crew,tags
0,"[Action, Adventure, Fantasy, ScienceFiction]",19995,"[cultureclash, future, spacewar, spacecolony, ...",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,"[Adventure, Fantasy, Action]",285,"[ocean, drugabuse, exoticisland, eastindiatrad...",Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,"[Action, Adventure, Crime]",206647,"[spy, basedonnovel, secretagent, sequel, mi6, ...",Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes],"[A, cryptic, message, from, Bondâ€™s, past, send..."

In [69]:
#create a new dataframe having columns id, title, tags.

In [33]:
new_df=movies[["movie_id","title","tags"]]

In [34]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [70]:
#convert tags from list to string.

In [35]:
new_df['tags']=new_df['tags'].apply(lambda x : " ".join(x))

C:\Users\jagadish\AppData\Local\Temp\ipykernel_7548\3060717092.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x : " ".join(x))

In [36]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [111]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [116]:
#convert tags to lowercase

In [37]:
new_df["tags"]=new_df["tags"].apply(lambda x : x.lower())

C:\Users\jagadish\AppData\Local\Temp\ipykernel_7548\2851446348.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["tags"]=new_df["tags"].apply(lambda x : x.lower())

In [30]:
new_df["tags"][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron'

#####use bag of words technique for making vectorization.
each tag is a vector.

In [ ]:
#stemming on tags

In [46]:
!pip install nltk

Requirement already satisfied: nltk in c:\users\jagadish\anaconda3\lib\site-packages (3.7)
Requirement already satisfied: joblib in c:\users\jagadish\anaconda3\lib\site-packages (from nltk) (1.1.0)
Requirement already satisfied: tqdm in c:\users\jagadish\anaconda3\lib\site-packages (from nltk) (4.64.0)
Requirement already satisfied: click in c:\users\jagadish\anaconda3\lib\site-packages (from nltk) (8.0.4)
Requirement already satisfied: regex>=2021.8.3 in c:\users\jagadish\anaconda3\lib\site-packages (from nltk) (2022.7.9)
Requirement already satisfied: colorama in c:\users\jagadish\anaconda3\lib\site-packages (from click->nltk) (0.4.5)

C:\Users\jagadish\AppData\Local\Temp\ipykernel_12204\3514595201.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)

In [38]:
import nltk

In [39]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [32]:
#example 1

print(ps.stem('loved'))
print(ps.stem('love'))
print(ps.stem('lovely'))
print(ps.stem('loving'))

love
love
love
love

In [33]:
#example 2

print(ps.stem('danced'))
print(ps.stem('dance'))
print(ps.stem('dancing'))

danc
danc
danc

In [40]:
def stem(text):
    y=[]
    string=""
    for i in text.split(): #split is used to convert string to list
        y.append(ps.stem(i))
        string = " ".join(y) #convert list back to string
    return string

In [ ]:
new_df['tags'][0]

In [41]:
new_df['tags']=new_df['tags'].apply(stem)

C:\Users\jagadish\AppData\Local\Temp\ipykernel_7548\3514595201.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)

In [42]:
new_df['tags']

0       in the 22nd century, a parapleg marin is dispa...
1       captain barbossa, long believ to be dead, ha c...
2       a cryptic messag from bondâ€™ past send him on a...
3       follow the death of district attorney harvey d...
4       john carter is a war-weary, former militari ca...
                              ...
4804    el mariachi just want to play hi guitar and ca...
4805    a newlyw couple' honeymoon is upend by the arr...
4806    "signed, sealed, delivered" introduc a dedic q...
4807    when ambiti new york attorney sam is sent to s...
4808    ever sinc the second grade when he first saw h...
Name: tags, Length: 4806, dtype: object

In [43]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=500,stop_words='english') 
#max_features is how many most common words are considered. 
#stop_words describes english stop words must be removed.

In [44]:
vectors=cv.fit_transform(new_df['tags']).toarray()

In [45]:
vectors.shape

(4806, 500)

In [39]:
vectors[0] #this gives the first movie.

array([1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [46]:
cv.get_feature_names() #this shows which 5000 common words are selected.

C:\Users\jagadish\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['3d',
 'accident',
 'act',
 'action',
 'adventur',
 'affair',
 'aftercreditssting',
 'age',
 'agent',
 'alcohol',
 'alien',
 'alway',
 'america',
 'american',
 'angel',
 'ani',
 'anim',
 'anoth',
 'apart',
 'armi',
 'arriv',
 'art',
 'artist',
 'assassin',
 'assign',
 'attack',
 'attempt',
 'author',
 'away',
 'babi',
 'bad',
 'band',
 'bank',
 'bar',
 'base',
 'basedonnovel',
 'battl',
 'beauti',
 'becom',
 'befor',
 'begin',
 'believ',
 'best',
 'big',
 'biographi',
 'black',
 'blood',
 'bond',
 'book',
 'boss',
 'boy',
 'boyfriend',
 'break',
 'bring',
 'british',
 'brother',
 'brutal',
 'busi',
 'california',
 'captain',
 'captur',
 'car',
 'career',
 'case',
 'caught',
 'caus',
 'celebr',
 'center',
 'chanc',
 'chang',
 'charact',
 'chase',
 'chicago',
 'child',
 'childhood',
 'children',
 'christian',
 'christma',
 'cia',
 'citi',
 'city',
 'class',
 'close',
 'coach',
 'colleg',
 'come',
 'comedi',
 'commun',
 'compani',
 'competit',
 'confront',
 'conspiraci',
 'continu',
 'control',
 'convinc',
 'cop',
 'corrupt',
 'countri',
 'coupl',
 'crash',
 'creat',
 'crew',
 'crime',
 'crimin',
 'cross',
 'danc',
 'danger',
 'dark',
 'date',
 'daughter',
 'day',
 'dead',
 'deadli',
 'deal',
 'death',
 'decid',
 'demon',
 'desert',
 'desper',
 'despit',
 'destroy',
 'detect',
 'determin',
 'develop',
 'die',
 'differ',
 'director',
 'disappear',
 'discov',
 'divorc',
 'doctor',
 'documentari',
 'doesn',
 'dog',
 'dr',
 'drama',
 'dream',
 'drug',
 'dure',
 'duringcreditssting',
 'dyinganddeath',
 'dystopia',
 'earth',
 'embark',
 'encount',
 'end',
 'england',
 'enter',
 'entir',
 'epic',
 'escap',
 'event',
 'everi',
 'everyon',
 'everyth',
 'evil',
 'ex',
 'execut',
 'experi',
 'explos',
 'eye',
 'face',
 'faith',
 'fall',
 'famili',
 'family',
 'fantasi',
 'far',
 'fate',
 'father',
 'fathersonrelationship',
 'fbi',
 'fear',
 'fight',
 'film',
 'final',
 'follow',
 'forc',
 'form',
 'frank',
 'free',
 'french',
 'friend',
 'friends',
 'friendship',
 'futur',
 'game',
 'gang',
 'gangster',
 'gay',
 'gener',
 'ghost',
 'girl',
 'girlfriend',
 'god',
 'goe',
 'good',
 'govern',
 'great',
 'group',
 'grow',
 'gun',
 'guy',
 'ha',
 'hand',
 'happen',
 'hard',
 'head',
 'heart',
 'heist',
 'help',
 'hero',
 'hi',
 'high',
 'highschool',
 'hire',
 'histori',
 'hit',
 'hold',
 'holiday',
 'hollywood',
 'home',
 'hope',
 'horror',
 'hospit',
 'hotel',
 'hous',
 'human',
 'hunt',
 'husband',
 'includ',
 'independentfilm',
 'inspir',
 'intern',
 'investig',
 'involv',
 'island',
 'jack',
 'jackson',
 'jame',
 'jean',
 'job',
 'john',
 'join',
 'journalist',
 'journey',
 'just',
 'kid',
 'kidnap',
 'kill',
 'killer',
 'king',
 'know',
 'known',
 'la',
 'land',
 'late',
 'later',
 'law',
 'lawyer',
 'lead',
 'leader',
 'learn',
 'leav',
 'led',
 'left',
 'lie',
 'life',
 'like',
 'littl',
 'live',
 'lives',
 'lo',
 'local',
 'london',
 'londonengland',
 'long',
 'look',
 'losangel',
 'lose',
 'lost',
 'love',
 'lover',
 'mafia',
 'magic',
 'make',
 'man',
 'manag',
 'mani',
 'marri',
 'marriag',
 'mean',
 'meet',
 'member',
 'men',
 'michael',
 'militari',
 'million',
 'miss',
 'mission',
 'money',
 'monster',
 'mother',
 'movi',
 'murder',
 'music',
 'mysteri',
 'nation',
 'need',
 'neighbor',
 'new',
 'newyork',
 'night',
 'noth',
 'nuditi',
 'obsess',
 'offic',
 'old',
 'onc',
 'onli',
 'open',
 'oper',
 'order',
 'owner',
 'pair',
 'parent',
 'pari',
 'parti',
 'partner',
 'past',
 'path',
 'peopl',
 'perfect',
 'person',
 'place',
 'plan',
 'planet',
 'play',
 'plot',
 'polic',
 'polit',
 'popular',
 'post',
 'power',
 'presid',
 'princess',
 'prison',
 'problem',
 'professor',
 'prostitut',
 'protect',
 'prove',
 'queen',
 'quest',
 'question',
 'race',
 'rais',
 'real',
 'realiz',
 'realli',
 'relationship',
 'remak',
 'report',
 'rescu',
 'retir',
 'return',
 'reveal',
 'reveng',
 'right',
 'rise',
 'road',
 'robot',
 'rock',
 'romanc',
 'romant',
 'rule',
 'run',
 'russian',
 'save',
 'school',
 'sciencefict',
 'scientist',
 'search',
 'secret',
 'secur',
 'seek',
 'self',
 'send',
 'sent',
 'sequel',
 'seri',
 'set',
 'sever',
 'sex',
 'sexual',
 'share',
 'sheriff',
 'ship',
 'singer',
 'singl',
 'sister',
 'small',
 'soldier',
 'someth',
 'son',
 'soon',
 'south',
 'space',
 'spend',
 'spi',
 'spirit',
 'sport',
 'stand',
 'star',
 'start',
 'state',
 'stay',
 'stop',
 'stori',
 'strang',
 'stranger',
 'street',
 'struggl',
 'student',
 'success',
 'suddenli',
 'suicid',
 'summer',
 'superhero',
 'supernatur',
 'surviv',
 'suspect',
 'suspens',
 'taken',
 'tale',
 'talent',
 'target',
 'teacher',
 'team',
 'teen',
 'teenag',
 'tell',
 'terror',
 'terrorist',
 'test',
 'themselv',
 'thi',
 'thing',
 'think',
 'threaten',
 'thriller',
 'time',
 'togeth',
 'town',
 'track',
 'train',
 'transform',
 'trap',
 'travel',
 'tri',
 'trip',
 'troubl',
 'true',
 'truth',
 'turn',
 'ultim',
 'uncov',
 'undercov',
 'unit',
 'unlik',
 'use',
 'vampir',
 'veri',
 'victim',
 'villag',
 'violenc',
 'visit',
 'wa',
 'want',
 'war',
 'way',
 'wed',
 'western',
 'white',
 'widow',
 'wife',
 'win',
 'wit',
 'witch',
 'woman',
 'womandirector',
 'women',
 'work',
 'world',
 'writer',
 'year',
 'years',
 'york',
 'young',
 'zombi']

In [81]:
#we have 4806 movies so 4806 vectors.
# find distance between each vector with every other vector to find the similarity.
#we use the angle between vectors to find the distance. 
#if angle is 0 then movie is same. if 180 then very dissimilar movies etc.
#cosine distance is used.
#distance is inversely proportional to similarity.

In [47]:
from sklearn.metrics.pairwise import cosine_similarity
#similarity ranges from 0 to 1. 
#if 1 highly similar.
#if 0 highly dissimilar

In [48]:
similarity=cosine_similarity(vectors)

In [49]:
similarity

array([[1.        , 0.17770466, 0.15789474, ..., 0.08377078, 0.        ,
        0.        ],
       [0.17770466, 1.        , 0.11846978, ..., 0.04714045, 0.        ,
        0.06262243],
       [0.15789474, 0.11846978, 1.        , ..., 0.04188539, 0.        ,
        0.        ],
       ...,
       [0.08377078, 0.04714045, 0.04188539, ..., 1.        , 0.07968191,
        0.08856149],
       [0.        , 0.        , 0.        , ..., 0.07968191, 1.        ,
        0.21170245],
       [0.        , 0.06262243, 0.        , ..., 0.08856149, 0.21170245,
        1.        ]])

In [44]:
similarity.shape

(4806, 4806)

In [45]:
similarity[0] #this gives the similarity value of 1st movie with every other movie.

array([1.        , 0.17770466, 0.15789474, ..., 0.08377078, 0.        ,
       0.        ])

In [50]:
#how to find index of a movie
new_df[new_df['title']=="Batman Begins"].index[0]

119

In [51]:
#def recommend(movie):
movie_index=new_df[new_df['title']=="Avatar"].index[0]
distances=similarity[movie_index]

In [97]:
distances #this shows the similarity of batman begins with every other movie.
#if we sort and find the last five movies, we can get the similar movies but the index is lost.

array([0.04783649, 0.10767638, 0.19134595, ..., 0.03806935, 0.22750788,
       0.15171652])

In [52]:
#to hold the movie index we will use enumerate.
#enumerate gives the enumerate object that has indexing from 0.
list(enumerate(distances))

[(0, 0.9999999999999997),
 (1, 0.17770466332772766),
 (2, 0.15789473684210523),
 (3, 0.1573778950729267),
 (4, 0.3211820274187865),
 (5, 0.27036903521793754),
 (6, 0.09567297464698797),
 (7, 0.23918243661746993),
 (8, 0.10814761408717502),
 (9, 0.1873171623163388),
 (10, 0.1835325870964494),
 (11, 0.1675415633166782),
 (12, 0.16222142113076254),
 (13, 0.09567297464698797),
 (14, 0.22941573387056174),
 (15, 0.13497638119975425),
 (16, 0.18394180184548975),
 (17, 0.2421000623531261),
 (18, 0.15609763526361564),
 (19, 0.20025046972870353),
 (20, 0.10196254838691632),
 (21, 0.21629522817435004),
 (22, 0.17342199390482396),
 (23, 0.2075143391598224),
 (24, 0.10526315789473682),
 (25, 0.064888568452305),
 (26, 0.2752988806446741),
 (27, 0.3594253787238923),
 (28, 0.24525573579398632),
 (29, 0.13006649542861798),
 (30, 0.13764944032233706),
 (31, 0.2545139051903111),
 (32, 0.17040572913692198),
 (33, 0.24333213169614376),
 (34, 0.0),
 (35, 0.2075143391598224),
 (36, 0.24722569302909872),
 (37, 0.18394180184548975),
 (38, 0.16481712868606582),
 (39, 0.16692446522239715),
 (40, 0.13006649542861798),
 (41, 0.30905754998184354),
 (42, 0.0),
 (43, 0.19564639521780736),
 (44, 0.059234887775909226),
 (45, 0.15974461276617435),
 (46, 0.2703690352179376),
 (47, 0.23424606849358912),
 (48, 0.15511334686589623),
 (49, 0.12725695259515554),
 (50, 0.2051956704170308),
 (51, 0.1835325870964494),
 (52, 0.21629522817435004),
 (53, 0.0899842541331695),
 (54, 0.0512989176042577),
 (55, 0.17342199390482396),
 (56, 0.26490647141300877),
 (57, 0.03823595564509362),
 (58, 0.12361284651454937),
 (59, 0.13834289277321493),
 (60, 0.030386856273138196),
 (61, 0.4291975376394761),
 (62, 0.17342199390482396),
 (63, 0.17040572913692198),
 (64, 0.06622661785325219),
 (65, 0.04891159880445184),
 (66, 0.04055535528269063),
 (67, 0.31578947368421045),
 (68, 0.24333213169614376),
 (69, 0.04732485242803009),
 (70, 0.17770466332772766),
 (71, 0.15018785229652765),
 (72, 0.2867696673382022),
 (73, 0.06362847629757777),
 (74, 0.37696851746252585),
 (75, 0.1720618004029213),
 (76, 0.13764944032233706),
 (77, 0.0324442842261525),
 (78, 0.11846977555181845),
 (79, 0.11803342130469503),
 (80, 0.08960215366342483),
 (81, 0.22329687826943603),
 (82, 0.15789473684210523),
 (83, 0.22329687826943606),
 (84, 0.2699527623995085),
 (85, 0.19918863762856528),
 (86, 0.1404878717372541),
 (87, 0.24525573579398632),
 (88, 0.14673479641335552),
 (89, 0.10526315789473682),
 (90, 0.12725695259515554),
 (91, 0.3338489304447943),
 (92, 0.13764944032233706),
 (93, 0.15789473684210523),
 (94, 0.2782074420373286),
 (95, 0.2445579940222592),
 (96, 0.15018785229652765),
 (97, 0.13006649542861798),
 (98, 0.2075143391598224),
 (99, 0.04891159880445184),
 (100, 0.13245323570650439),
 (101, 0.14350946197048195),
 (102, 0.25560859370538297),
 (103, 0.15511334686589623),
 (104, 0.11128297681493143),
 (105, 0.19088542889273333),
 (106, 0.12166606584807188),
 (107, 0.12780429685269148),
 (108, 0.24333213169614376),
 (109, 0.12262786789699316),
 (110, 0.10012523486435176),
 (111, 0.26013299085723596),
 (112, 0.15018785229652765),
 (113, 0.08671099695241198),
 (114, 0.10526315789473682),
 (115, 0.08111071056538126),
 (116, 0.0899842541331695),
 (117, 0.11470786693528087),
 (118, 0.0734718358370645),
 (119, 0.047836487323493986),
 (120, 0.0),
 (121, 0.21629522817435007),
 (122, 0.22256595362986287),
 (123, 0.23414645289542352),
 (124, 0.10882143751650174),
 (125, 0.16452254913212452),
 (126, 0.2564945880212885),
 (127, 0.24975621642178503),
 (128, 0.0),
 (129, 0.16481712868606582),
 (130, 0.042601432284230495),
 (131, 0.1835325870964494),
 (132, 0.07868894753646336),
 (133, 0.05564148840746572),
 (134, 0.24525573579398632),
 (135, 0.0),
 (136, 0.05006261743217588),
 (137, 0.06622661785325219),
 (138, 0.2445579940222592),
 (139, 0.22629428592141426),
 (140, 0.07868894753646336),
 (141, 0.19088542889273333),
 (142, 0.11470786693528087),
 (143, 0.17342199390482396),
 (144, 0.0936585811581694),
 (145, 0.03934447376823168),
 (146, 0.027226638505866502),
 (147, 0.11846977555181845),
 (148, 0.2075143391598224),
 (149, 0.26401000024165),
 (150, 0.3264643125495052),
 (151, 0.4866642633922876),
 (152, 0.14673479641335552),
 (153, 0.1399422857082639),
 (154, 0.11128297681493143),
 (155, 0.04588314677411235),
 (156, 0.13497638119975425),
 (157, 0.21764287503300347),
 (158, 0.1835325870964494),
 (159, 0.17342199390482396),
 (160, 0.24489899998946185),
 (161, 0.06917144638660747),
 (162, 0.07254762501100116),
 (163, 0.10814761408717502),
 (164, 0.16692446522239715),
 (165, 0.0917662935482247),
 (166, 0.23414645289542352),
 (167, 0.16222142113076254),
 (168, 0.29319773580418684),
 (169, 0.17660431427533915),
 (170, 0.20277677641345315),
 (171, 0.03934447376823168),
 (172, 0.3554093266554553),
 (173, 0.047836487323493986),
 (174, 0.13764944032233706),
 (175, 0.1538967528127731),
 (176, 0.06131393394849658),
 (177, 0.0),
 (178, 0.04188539082916955),
 (179, 0.12725695259515554),
 (180, 0.042601432284230495),
 (181, 0.12725695259515554),
 (182, 0.21677749238102995),
 (183, 0.13109470506889243),
 (184, 0.30348848933344197),
 (185, 0.0917662935482247),
 (186, 0.15789473684210523),
 (187, 0.2699527623995085),
 (188, 0.04335549847620599),
 (189, 0.22941573387056172),
 (190, 0.1573778950729267),
 (191, 0.0899842541331695),
 (192, 0.11470786693528087),
 (193, 0.12590824129146974),
 (194, 0.0),
 (195, 0.1025978352085154),
 (196, 0.09782319760890368),
 (197, 0.06424925662032355),
 (198, 0.11128297681493143),
 (199, 0.21629522817435004),
 (200, 0.22941573387056172),
 (201, 0.0),
 (202, 0.06622661785325219),
 (203, 0.1720618004029213),
 (204, 0.11846977555181845),
 (205, 0.14509525002200233),
 (206, 0.18232113763882918),
 (207, 0.17770466332772766),
 (208, 0.32444284226152503),
 (209, 0.12725695259515554),
 (210, 0.18394180184548975),
 (211, 0.05263157894736841),
 (212, 0.12565617248750865),
 (213, 0.11633501014942217),
 (214, 0.0),
 (215, 0.13764944032233706),
 (216, 0.15294382258037448),
 (217, 0.17660431427533915),
 (218, 0.07254762501100116),
 (219, 0.1986798535597566),
 (220, 0.33384893044479425),
 (221, 0.09567297464698797),
 (222, 0.14509525002200233),
 (223, 0.21629522817435004),
 (224, 0.10748615458500278),
 (225, 0.08240856434303291),
 (226, 0.07254762501100116),
 (227, 0.1720618004029213),
 (228, 0.20602141085758227),
 (229, 0.25131234497501725),
 (230, 0.1911797782254681),
 (231, 0.0),
 (232, 0.22941573387056174),
 (233, 0.22941573387056172),
 (234, 0.15086285728094284),
 (235, 0.12780429685269148),
 (236, 0.11846977555181845),
 (237, 0.12725695259515554),
 (238, 0.22629428592141426),
 (239, 0.1911797782254681),
 (240, 0.10814761408717502),
 (241, 0.16692446522239715),
 (242, 0.16222142113076254),
 (243, 0.21629522817435007),
 (244, 0.1720618004029213),
 (245, 0.18394180184548975),
 (246, 0.13530201829834765),
 (247, 0.0),
 (248, 0.08830215713766958),
 (249, 0.18394180184548975),
 (250, 0.0),
 (251, 0.07647191129018724),
 (252, 0.04055535528269063),
 (253, 0.1404878717372541),
 (254, 0.09567297464698797),
 (255, 0.0),
 (256, 0.2176428750330035),
 (257, 0.0936585811581694),
 (258, 0.03498557142706597),
 (259, 0.13834289277321493),
 (260, 0.3244428422615251),
 (261, 0.0512989176042577),
 (262, 0.22941573387056174),
 (263, 0.1986798535597566),
 (264, 0.0),
 (265, 0.07647191129018724),
 (266, 0.15294382258037448),
 (267, 0.12725695259515554),
 (268, 0.09782319760890368),
 (269, 0.0512989176042577),
 (270, 0.17660431427533915),
 (271, 0.16692446522239715),
 (272, 0.05263157894736841),
 (273, 0.04055535528269063),
 (274, 0.16059101370939322),
 (275, 0.2051956704170308),
 (276, 0.13245323570650439),
 (277, 0.09832102880166932),
 (278, 0.16222142113076254),
 (279, 0.13006649542861798),
 (280, 0.0),
 (281, 0.0512989176042577),
 (282, 0.03498557142706597),
 (283, 0.0),
 (284, 0.03823595564509362),
 (285, 0.03721614637823934),
 (286, 0.14886458551295736),
 (287, 0.0),
 (288, 0.059234887775909226),
 (289, 0.07868894753646336),
 (290, 0.15294382258037448),
 (291, 0.12262786789699316),
 (292, 0.16222142113076254),
 (293, 0.057353933467640436),
 (294, 0.2341464528954235),
 (295, 0.17660431427533915),
 (296, 0.07443229275647868),
 (297, 0.11128297681493143),
 (298, 0.0),
 (299, 0.14673479641335552),
 (300, 0.2649064714130087),
 (301, 0.21300716142115247),
 (302, 0.16222142113076254),
 (303, 0.07254762501100116),
 (304, 0.10696563746013953),
 (305, 0.3973597071195131),
 (306, 0.1720618004029213),
 (307, 0.2205887220821391),
 (308, 0.11470786693528087),
 (309, 0.13245323570650439),
 (310, 0.06997114285413195),
 (311, 0.15789473684210523),
 (312, 0.15789473684210523),
 (313, 0.08830215713766958),
 (314, 0.0),
 (315, 0.17770466332772766),
 (316, 0.0),
 (317, 0.0),
 (318, 0.0),
 (319, 0.1908854288927333),
 (320, 0.06917144638660747),
 (321, 0.0),
 (322, 0.44539933408304444),
 (323, 0.05564148840746572),
 (324, 0.057353933467640436),
 (325, 0.1720618004029213),
 (326, 0.12725695259515554),
 (327, 0.06622661785325219),
 (328, 0.04891159880445184),
 (329, 0.16222142113076254),
 (330, 0.24525573579398632),
 (331, 0.15294382258037448),
 (332, 0.23693955110363688),
 (333, 0.057353933467640436),
 (334, 0.21629522817435004),
 (335, 0.1025978352085154),
 (336, 0.15294382258037448),
 (337, 0.08520286456846099),
 (338, 0.0),
 (339, 0.08240856434303291),
 (340, 0.12262786789699316),
 (341, 0.14350946197048195),
 (342, 0.27348170645824377),
 (343, 0.04415107856883479),
 (344, 0.06362847629757777),
 (345, 0.04588314677411235),
 (346, 0.0),
 (347, 0.0),
 (348, 0.12725695259515554),
 (349, 0.19088542889273333),
 (350, 0.1025978352085154),
 (351, 0.0),
 (352, 0.05263157894736841),
 (353, 0.10526315789473682),
 (354, 0.04588314677411235),
 (355, 0.07868894753646336),
 (356, 0.1720618004029213),
 (357, 0.0),
 (358, 0.13245323570650439),
 (359, 0.05263157894736841),
 (360, 0.041204282171516456),
 (361, 0.15018785229652765),
 (362, 0.18394180184548975),
 (363, 0.20942695414584772),
 (364, 0.04055535528269063),
 (365, 0.15018785229652765),
 (366, 0.10814761408717502),
 (367, 0.0),
 (368, 0.23693955110363688),
 (369, 0.2075143391598224),
 (370, 0.0917662935482247),
 (371, 0.20025046972870353),
 (372, 0.0837707816583391),
 (373, 0.32444284226152503),
 (374, 0.0734718358370645),
 (375, 0.0837707816583391),
 (376, 0.0899842541331695),
 (377, 0.0),
 (378, 0.0),
 (379, 0.11470786693528086),
 (380, 0.10814761408717502),
 (381, 0.15294382258037448),
 (382, 0.0),
 (383, 0.08671099695241198),
 (384, 0.06917144638660747),
 (385, 0.0),
 (386, 0.04055535528269063),
 (387, 0.04499212706658475),
 (388, 0.0),
 (389, 0.2075143391598224),
 (390, 0.05006261743217588),
 (391, 0.09453802374948816),
 (392, 0.05263157894736841),
 (393, 0.0),
 (394, 0.05564148840746572),
 (395, 0.08830215713766958),
 (396, 0.0936585811581694),
 (397, 0.11470786693528087),
 (398, 0.0),
 (399, 0.05263157894736841),
 (400, 0.15018785229652765),
 (401, 0.05263157894736841),
 (402, 0.15789473684210523),
 (403, 0.146943671674129),
 (404, 0.06131393394849658),
 (405, 0.11846977555181845),
 (406, 0.04335549847620599),
 (407, 0.04891159880445184),
 (408, 0.059234887775909226),
 (409, 0.0),
 (410, 0.17342199390482396),
 (411, 0.11846977555181845),
 (412, 0.19564639521780736),
 (413, 0.2782074420373286),
 (414, 0.057353933467640436),
 (415, 0.0837707816583391),
 (416, 0.11470786693528087),
 (417, 0.07254762501100116),
 (418, 0.06917144638660747),
 (419, 0.15018785229652765),
 (420, 0.1967223688411584),
 (421, 0.042601432284230495),
 (422, 0.24333213169614376),
 (423, 0.03934447376823168),
 (424, 0.0899842541331695),
 (425, 0.11980845957463077),
 (426, 0.10259783520851541),
 (427, 0.05564148840746572),
 (428, 0.14673479641335552),
 (429, 0.0),
 (430, 0.0917662935482247),
 (431, 0.047836487323493986),
 (432, 0.179968508266339),
 (433, 0.05564148840746572),
 (434, 0.0),
 (435, 0.06362847629757777),
 (436, 0.0),
 (437, 0.05006261743217588),
 (438, 0.047836487323493986),
 (439, 0.0468292905790847),
 (440, 0.0512989176042577),
 (441, 0.09782319760890368),
 (442, 0.08111071056538126),
 (443, 0.11020775375559674),
 (444, 0.0),
 (445, 0.1835325870964494),
 (446, 0.04891159880445184),
 (447, 0.13497638119975425),
 (448, 0.03673591791853225),
 (449, 0.1873171623163388),
 (450, 0.03498557142706597),
 (451, 0.057353933467640436),
 (452, 0.06362847629757777),
 (453, 0.057353933467640436),
 (454, 0.2503130871608794),
 (455, 0.11633501014942217),
 (456, 0.0936585811581694),
 (457, 0.15789473684210523),
 (458, 0.08671099695241198),
 (459, 0.06131393394849658),
 (460, 0.04055535528269063),
 (461, 0.2961744388795461),
 (462, 0.058271654674806495),
 (463, 0.05564148840746572),
 (464, 0.0),
 (465, 0.0),
 (466, 0.29019050004400465),
 (467, 0.2703690352179376),
 (468, 0.057353933467640436),
 (469, 0.10495671428119792),
 (470, 0.1025978352085154),
 (471, 0.10882143751650175),
 (472, 0.19564639521780736),
 (473, 0.2051956704170308),
 (474, 0.0),
 (475, 0.11128297681493143),
 (476, 0.16222142113076254),
 (477, 0.0),
 (478, 0.11633501014942217),
 (479, 0.19968076595771794),
 (480, 0.17660431427533915),
 (481, 0.0),
 (482, 0.03539961627023943),
 (483, 0.21629522817435004),
 (484, 0.059234887775909226),
 (485, 0.12725695259515554),
 (486, 0.13425540338526368),
 (487, 0.2545139051903111),
 (488, 0.10039117221153818),
 (489, 0.0),
 (490, 0.27668578554642986),
 (491, 0.18367958959266123),
 (492, 0.12780429685269148),
 (493, 0.05298129428260174),
 (494, 0.0),
 (495, 0.3338489304447943),
 (496, 0.0),
 (497, 0.0),
 (498, 0.11846977555181845),
 (499, 0.0),
 (500, 0.05564148840746572),
 (501, 0.13109470506889243),
 (502, 0.2699527623995085),
 (503, 0.13764944032233706),
 (504, 0.0),
 (505, 0.2545139051903111),
 (506, 0.07647191129018724),
 (507, 0.5619514869490164),
 (508, 0.2369395511036369),
 (509, 0.04588314677411235),
 (510, 0.19134594929397594),
 (511, 0.2075143391598224),
 (512, 0.059234887775909226),
 (513, 0.14509525002200233),
 (514, 0.0917662935482247),
 (515, 0.05564148840746572),
 (516, 0.057353933467640436),
 (517, 0.0),
 (518, 0.08111071056538126),
 (519, 0.0),
 (520, 0.0),
 (521, 0.05564148840746572),
 (522, 0.04588314677411235),
 (523, 0.10526315789473682),
 (524, 0.0),
 (525, 0.09567297464698797),
 (526, 0.057353933467640436),
 (527, 0.059234887775909226),
 (528, 0.047836487323493986),
 (529, 0.3077935056255462),
 (530, 0.0917662935482247),
 (531, 0.08671099695241198),
 (532, 0.04188539082916955),
 (533, 0.10012523486435176),
 (534, 0.15294382258037448),
 (535, 0.14673479641335552),
 (536, 0.1967223688411584),
 (537, 0.15294382258037448),
 (538, 0.0),
 (539, 0.4305283859114459),
 (540, 0.14350946197048195),
 (541, 0.179968508266339),
 (542, 0.07755667343294811),
 (543, 0.14673479641335552),
 (544, 0.10012523486435176),
 (545, 0.04588314677411235),
 (546, 0.14509525002200233),
 (547, 0.1720618004029213),
 (548, 0.0),
 (549, 0.2782074420373286),
 (550, 0.05263157894736841),
 (551, 0.07987230638308718),
 (552, 0.0),
 (553, 0.04891159880445184),
 (554, 0.0),
 (555, 0.07894736842105261),
 (556, 0.057353933467640436),
 (557, 0.042601432284230495),
 (558, 0.0),
 (559, 0.04891159880445184),
 (560, 0.061868822488974594),
 (561, 0.06917144638660747),
 (562, 0.059234887775909226),
 (563, 0.04415107856883479),
 (564, 0.1908854288927333),
 (565, 0.08520286456846099),
 (566, 0.047836487323493986),
 (567, 0.047836487323493986),
 (568, 0.2503130871608794),
 (569, 0.07868894753646336),
 (570, 0.08111071056538126),
 (571, 0.08240856434303291),
 (572, 0.20277677641345315),
 (573, 0.04335549847620599),
 (574, 0.04499212706658475),
 (575, 0.07755667343294811),
 (576, 0.08830215713766958),
 (577, 0.38949041885226),
 (578, 0.07543142864047142),
 (579, 0.26315789473684204),
 (580, 0.05006261743217588),
 (581, 0.27036903521793754),
 (582, 0.30348848933344197),
 (583, 0.06554735253444621),
 (584, 0.1873171623163388),
 (585, 0.04588314677411235),
 (586, 0.0899842541331695),
 (587, 0.1538967528127731),
 (588, 0.05564148840746572),
 (589, 0.21497230917000557),
 (590, 0.05407380704358751),
 (591, 0.10748615458500278),
 (592, 0.03823595564509362),
 (593, 0.0),
 (594, 0.10814761408717502),
 (595, 0.23918243661746993),
 (596, 0.19134594929397594),
 (597, 0.1025978352085154),
 (598, 0.059234887775909226),
 (599, 0.050669459193813986),
 (600, 0.16222142113076254),
 (601, 0.057807331301607985),
 (602, 0.16222142113076252),
 (603, 0.11846977555181845),
 (604, 0.12262786789699316),
 (605, 0.05564148840746572),
 (606, 0.0),
 (607, 0.09832102880166932),
 (608, 0.0),
 (609, 0.0837707816583391),
 (610, 0.09464970485606018),
 (611, 0.04415107856883479),
 (612, 0.13245323570650436),
 (613, 0.06622661785325219),
 (614, 0.05407380704358751),
 (615, 0.12262786789699316),
 (616, 0.06917144638660747),
 (617, 0.0512989176042577),
 (618, 0.15974461276617435),
 (619, 0.0),
 (620, 0.0),
 (621, 0.13245323570650439),
 (622, 0.04415107856883479),
 (623, 0.0),
 (624, 0.19088542889273333),
 (625, 0.06362847629757777),
 (626, 0.15018785229652765),
 (627, 0.24333213169614376),
 (628, 0.0),
 (629, 0.08520286456846099),
 (630, 0.04588314677411235),
 (631, 0.11470786693528087),
 (632, 0.16222142113076254),
 (633, 0.0468292905790847),
 (634, 0.11128297681493143),
 (635, 0.10526315789473682),
 (636, 0.04188539082916955),
 (637, 0.0512989176042577),
 (638, 0.07254762501100116),
 (639, 0.0),
 (640, 0.10882143751650175),
 (641, 0.0),
 (642, 0.0),
 (643, 0.16222142113076254),
 (644, 0.09567297464698797),
 (645, 0.10526315789473682),
 (646, 0.047836487323493986),
 (647, 0.0),
 (648, 0.06362847629757777),
 (649, 0.0),
 (650, 0.0917662935482247),
 (651, 0.0),
 (652, 0.09782319760890368),
 (653, 0.17770466332772766),
 (654, 0.20942695414584772),
 (655, 0.04891159880445184),
 (656, 0.0),
 (657, 0.07254762501100116),
 (658, 0.09567297464698797),
 (659, 0.04588314677411235),
 (660, 0.18394180184548975),
 (661, 0.31022669373179246),
 (662, 0.0),
 (663, 0.0),
 (664, 0.10526315789473682),
 (665, 0.14350946197048195),
 (666, 0.10814761408717502),
 (667, 0.0),
 (668, 0.22941573387056174),
 (669, 0.06917144638660747),
 (670, 0.031814238148788886),
 (671, 0.1538967528127731),
 (672, 0.047836487323493986),
 (673, 0.03721614637823934),
 (674, 0.08520286456846099),
 (675, 0.12725695259515554),
 (676, 0.05407380704358751),
 (677, 0.047836487323493986),
 (678, 0.21052631578947364),
 (679, 0.0),
 (680, 0.15789473684210523),
 (681, 0.06131393394849658),
 (682, 0.03346372407051273),
 (683, 0.09782319760890368),
 (684, 0.0),
 (685, 0.06917144638660747),
 (686, 0.05407380704358751),
 (687, 0.1835325870964494),
 (688, 0.07755667343294811),
 (689, 0.0),
 (690, 0.05564148840746572),
 (691, 0.13245323570650439),
 (692, 0.1967223688411584),
 (693, 0.06131393394849658),
 (694, 0.04415107856883479),
 (695, 0.15294382258037448),
 (696, 0.03993615319154359),
 (697, 0.0),
 (698, 0.07868894753646336),
 (699, 0.06362847629757777),
 (700, 0.05263157894736841),
 (701, 0.12262786789699316),
 (702, 0.04588314677411235),
 (703, 0.05006261743217588),
 (704, 0.12780429685269148),
 (705, 0.04891159880445184),
 (706, 0.03934447376823168),
 (707, 0.0),
 (708, 0.05407380704358751),
 (709, 0.03627381250550058),
 (710, 0.10619884881071828),
 (711, 0.0837707816583391),
 (712, 0.0),
 (713, 0.0512989176042577),
 (714, 0.0),
 (715, 0.22941573387056172),
 (716, 0.047836487323493986),
 (717, 0.0),
 (718, 0.13834289277321493),
 (719, 0.0),
 (720, 0.07647191129018724),
 (721, 0.06917144638660747),
 (722, 0.0),
 (723, 0.0468292905790847),
 (724, 0.04499212706658475),
 (725, 0.0),
 (726, 0.0),
 (727, 0.05298129428260174),
 (728, 0.13497638119975425),
 (729, 0.08111071056538126),
 (730, 0.059234887775909226),
 (731, 0.08671099695241198),
 (732, 0.16222142113076254),
 (733, 0.11633501014942217),
 (734, 0.12780429685269148),
 (735, 0.14350946197048195),
 (736, 0.05564148840746572),
 (737, 0.0468292905790847),
 (738, 0.0),
 (739, 0.07254762501100116),
 (740, 0.19564639521780736),
 (741, 0.09782319760890368),
 (742, 0.05263157894736841),
 (743, 0.04188539082916955),
 (744, 0.13245323570650439),
 (745, 0.16222142113076254),
 (746, 0.14350946197048195),

In [53]:
#lets sort it in descending order.
sorted(list(enumerate(distances)),reverse=True)
# this is sorting based on index. but we need to sort based on similarity.

[(4805, 0.0),
 (4804, 0.0),
 (4803, 0.0837707816583391),
 (4802, 0.13245323570650439),
 (4801, 0.03382550457458691),
 (4800, 0.0),
 (4799, 0.06131393394849658),
 (4798, 0.03877833671647406),
 (4797, 0.0),
 (4796, 0.0),
 (4795, 0.0),
 (4794, 0.0),
 (4793, 0.0),
 (4792, 0.0),
 (4791, 0.0),
 (4790, 0.13245323570650439),
 (4789, 0.10619884881071828),
 (4788, 0.0),
 (4787, 0.03627381250550058),
 (4786, 0.0),
 (4785, 0.03458572319330373),
 (4784, 0.06917144638660747),
 (4783, 0.0),
 (4782, 0.0),
 (4781, 0.057353933467640436),
 (4780, 0.0),
 (4779, 0.0),
 (4778, 0.0),
 (4777, 0.17342199390482396),
 (4776, 0.0),
 (4775, 0.11470786693528087),
 (4774, 0.0),
 (4773, 0.0512989176042577),
 (4772, 0.041204282171516456),
 (4771, 0.06917144638660747),
 (4770, 0.0),
 (4769, 0.0),
 (4768, 0.0),
 (4767, 0.06917144638660747),
 (4766, 0.03382550457458691),
 (4765, 0.0),
 (4764, 0.0),
 (4763, 0.0),
 (4762, 0.0),
 (4761, 0.05263157894736841),
 (4760, 0.05407380704358751),
 (4759, 0.04055535528269063),
 (4758, 0.0),
 (4757, 0.08111071056538126),
 (4756, 0.0),
 (4755, 0.04415107856883479),
 (4754, 0.14673479641335552),
 (4753, 0.0),
 (4752, 0.05407380704358751),
 (4751, 0.04335549847620599),
 (4750, 0.0),
 (4749, 0.0),
 (4748, 0.041204282171516456),
 (4747, 0.0),
 (4746, 0.0),
 (4745, 0.0),
 (4744, 0.06622661785325219),
 (4743, 0.023918243661746993),
 (4742, 0.06131393394849658),
 (4741, 0.0),
 (4740, 0.0),
 (4739, 0.042601432284230495),
 (4738, 0.0),
 (4737, 0.12725695259515554),
 (4736, 0.0),
 (4735, 0.0),
 (4734, 0.042061011686753615),
 (4733, 0.0),
 (4732, 0.0),
 (4731, 0.06131393394849658),
 (4730, 0.04335549847620599),
 (4729, 0.0),
 (4728, 0.0),
 (4727, 0.1025978352085154),
 (4726, 0.0),
 (4725, 0.0),
 (4724, 0.0),
 (4723, 0.0),
 (4722, 0.08671099695241198),
 (4721, 0.0),
 (4720, 0.0512989176042577),
 (4719, 0.0),
 (4718, 0.06622661785325219),
 (4717, 0.0),
 (4716, 0.0),
 (4715, 0.0),
 (4714, 0.0),
 (4713, 0.04588314677411235),
 (4712, 0.04055535528269063),
 (4711, 0.12565617248750863),
 (4710, 0.0),
 (4709, 0.0),
 (4708, 0.0),
 (4707, 0.05263157894736841),
 (4706, 0.023662426214015046),
 (4705, 0.0),
 (4704, 0.11846977555181845),
 (4703, 0.06362847629757777),
 (4702, 0.0),
 (4701, 0.0),
 (4700, 0.05407380704358751),
 (4699, 0.0917662935482247),
 (4698, 0.0),
 (4697, 0.0),
 (4696, 0.02845551966122361),
 (4695, 0.06243905410544626),
 (4694, 0.03993615319154359),
 (4693, 0.10526315789473682),
 (4692, 0.0),
 (4691, 0.10012523486435176),
 (4690, 0.06131393394849658),
 (4689, 0.0),
 (4688, 0.0),
 (4687, 0.0),
 (4686, 0.0),
 (4685, 0.0),
 (4684, 0.0),
 (4683, 0.0),
 (4682, 0.0),
 (4681, 0.0),
 (4680, 0.12262786789699316),
 (4679, 0.07254762501100116),
 (4678, 0.0),
 (4677, 0.0),
 (4676, 0.0),
 (4675, 0.06131393394849658),
 (4674, 0.03721614637823934),
 (4673, 0.22941573387056174),
 (4672, 0.11846977555181845),
 (4671, 0.059234887775909226),
 (4670, 0.06554735253444621),
 (4669, 0.06362847629757777),
 (4668, 0.0),
 (4667, 0.04499212706658475),
 (4666, 0.05263157894736841),
 (4665, 0.0),
 (4664, 0.09782319760890368),
 (4663, 0.0),
 (4662, 0.04891159880445184),
 (4661, 0.057353933467640436),
 (4660, 0.0),
 (4659, 0.057353933467640436),
 (4658, 0.0),
 (4657, 0.1538967528127731),
 (4656, 0.030386856273138196),
 (4655, 0.06362847629757777),
 (4654, 0.16222142113076252),
 (4653, 0.0),
 (4652, 0.10526315789473682),
 (4651, 0.07647191129018724),
 (4650, 0.0),
 (4649, 0.0),
 (4648, 0.032773676267223106),
 (4647, 0.03673591791853225),
 (4646, 0.06622661785325219),
 (4645, 0.0),
 (4644, 0.0),
 (4643, 0.06622661785325219),
 (4642, 0.059234887775909226),
 (4641, 0.13245323570650439),
 (4640, 0.04891159880445184),
 (4639, 0.0),
 (4638, 0.12262786789699316),
 (4637, 0.0),
 (4636, 0.13245323570650439),
 (4635, 0.06622661785325219),
 (4634, 0.059234887775909226),
 (4633, 0.059234887775909226),
 (4632, 0.07647191129018724),
 (4631, 0.0),
 (4630, 0.061868822488974594),
 (4629, 0.059234887775909226),
 (4628, 0.0),
 (4627, 0.07254762501100116),
 (4626, 0.14350946197048195),
 (4625, 0.0),
 (4624, 0.13497638119975425),
 (4623, 0.13245323570650439),
 (4622, 0.07254762501100116),
 (4621, 0.0),
 (4620, 0.0),
 (4619, 0.07647191129018724),
 (4618, 0.0),
 (4617, 0.0),
 (4616, 0.0),
 (4615, 0.0),
 (4614, 0.0),
 (4613, 0.0),
 (4612, 0.0),
 (4611, 0.059234887775909226),
 (4610, 0.0),
 (4609, 0.0),
 (4608, 0.0),
 (4607, 0.042601432284230495),
 (4606, 0.07254762501100116),
 (4605, 0.05564148840746572),
 (4604, 0.057353933467640436),
 (4603, 0.0),
 (4602, 0.09782319760890368),
 (4601, 0.0),
 (4600, 0.03934447376823168),
 (4599, 0.0),
 (4598, 0.0),
 (4597, 0.04335549847620599),
 (4596, 0.0936585811581694),
 (4595, 0.0),
 (4594, 0.0),
 (4593, 0.0),
 (4592, 0.0),
 (4591, 0.05006261743217588),
 (4590, 0.10012523486435176),
 (4589, 0.05407380704358751),
 (4588, 0.0),
 (4587, 0.14509525002200233),
 (4586, 0.0),
 (4585, 0.0),
 (4584, 0.0),
 (4583, 0.0),
 (4582, 0.14673479641335552),
 (4581, 0.07254762501100116),
 (4580, 0.07647191129018724),
 (4579, 0.05407380704358751),
 (4578, 0.08671099695241198),
 (4577, 0.0),
 (4576, 0.042601432284230495),
 (4575, 0.0),
 (4574, 0.03498557142706597),
 (4573, 0.06917144638660747),
 (4572, 0.0),
 (4571, 0.0),
 (4570, 0.06131393394849658),
 (4569, 0.05564148840746572),
 (4568, 0.15294382258037448),
 (4567, 0.0),
 (4566, 0.13834289277321493),
 (4565, 0.03382550457458691),
 (4564, 0.0936585811581694),
 (4563, 0.0),
 (4562, 0.0),
 (4561, 0.0),
 (4560, 0.14673479641335552),
 (4559, 0.031512674583162724),
 (4558, 0.14673479641335552),
 (4557, 0.06622661785325219),
 (4556, 0.0),
 (4555, 0.06917144638660747),
 (4554, 0.07254762501100116),
 (4553, 0.0),
 (4552, 0.08671099695241198),
 (4551, 0.0),
 (4550, 0.0),
 (4549, 0.05263157894736841),
 (4548, 0.0),
 (4547, 0.0),
 (4546, 0.0),
 (4545, 0.21677749238102995),
 (4544, 0.0),
 (4543, 0.059234887775909226),
 (4542, 0.11470786693528087),
 (4541, 0.0),
 (4540, 0.10814761408717502),
 (4539, 0.0),
 (4538, 0.29346959282671103),
 (4537, 0.0),
 (4536, 0.05263157894736841),
 (4535, 0.059234887775909226),
 (4534, 0.0),
 (4533, 0.08111071056538126),
 (4532, 0.06302534916632545),
 (4531, 0.0),
 (4530, 0.0899842541331695),
 (4529, 0.019320290100197885),
 (4528, 0.0936585811581694),
 (4527, 0.0),
 (4526, 0.0),
 (4525, 0.08830215713766958),
 (4524, 0.07647191129018724),
 (4523, 0.0),
 (4522, 0.02459594839716409),
 (4521, 0.0),
 (4520, 0.0),
 (4519, 0.08520286456846099),
 (4518, 0.0),
 (4517, 0.0),
 (4516, 0.13834289277321493),
 (4515, 0.0),
 (4514, 0.04891159880445184),
 (4513, 0.0),
 (4512, 0.08240856434303291),
 (4511, 0.04891159880445184),
 (4510, 0.0),
 (4509, 0.0),
 (4508, 0.0),
 (4507, 0.0),
 (4506, 0.11314714296070713),
 (4505, 0.04891159880445184),
 (4504, 0.0),
 (4503, 0.0),
 (4502, 0.16222142113076252),
 (4501, 0.0),
 (4500, 0.0),
 (4499, 0.0),
 (4498, 0.05407380704358751),
 (4497, 0.0),
 (4496, 0.0),
 (4495, 0.0),
 (4494, 0.0),
 (4493, 0.0),
 (4492, 0.13834289277321493),
 (4491, 0.0),
 (4490, 0.18394180184548975),
 (4489, 0.03539961627023943),
 (4488, 0.0),
 (4487, 0.03721614637823934),
 (4486, 0.057353933467640436),
 (4485, 0.0512989176042577),
 (4484, 0.0),
 (4483, 0.12166606584807188),
 (4482, 0.06131393394849658),
 (4481, 0.0),
 (4480, 0.0),
 (4479, 0.0),
 (4478, 0.0),
 (4477, 0.06131393394849658),
 (4476, 0.0),
 (4475, 0.0),
 (4474, 0.06917144638660747),
 (4473, 0.13834289277321493),
 (4472, 0.2075143391598224),
 (4471, 0.09567297464698797),
 (4470, 0.0),
 (4469, 0.06917144638660747),
 (4468, 0.19564639521780736),
 (4467, 0.04891159880445184),
 (4466, 0.07254762501100116),
 (4465, 0.0),
 (4464, 0.0),
 (4463, 0.06917144638660747),
 (4462, 0.0),
 (4461, 0.0),
 (4460, 0.07254762501100116),
 (4459, 0.08671099695241198),
 (4458, 0.10814761408717502),
 (4457, 0.0),
 (4456, 0.0),
 (4455, 0.0),
 (4454, 0.0),
 (4453, 0.06839855680567694),
 (4452, 0.0),
 (4451, 0.07868894753646336),
 (4450, 0.04588314677411235),
 (4449, 0.0),
 (4448, 0.06781501183626365),
 (4447, 0.0),
 (4446, 0.04499212706658475),
 (4445, 0.0),
 (4444, 0.0),
 (4443, 0.11470786693528087),
 (4442, 0.0),
 (4441, 0.0),
 (4440, 0.0),
 (4439, 0.0),
 (4438, 0.0),
 (4437, 0.06362847629757777),
 (4436, 0.0),
 (4435, 0.0),
 (4434, 0.057353933467640436),
 (4433, 0.06131393394849658),
 (4432, 0.0),
 (4431, 0.11128297681493143),
 (4430, 0.0),
 (4429, 0.09197090092274487),
 (4428, 0.0),
 (4427, 0.08111071056538126),
 (4426, 0.0),
 (4425, 0.0),
 (4424, 0.0),
 (4423, 0.0),
 (4422, 0.05407380704358751),
 (4421, 0.05564148840746572),
 (4420, 0.047836487323493986),
 (4419, 0.0),
 (4418, 0.0),
 (4417, 0.0),
 (4416, 0.0),
 (4415, 0.0),
 (4414, 0.05263157894736841),
 (4413, 0.03771571432023571),
 (4412, 0.06622661785325219),
 (4411, 0.0),
 (4410, 0.0512989176042577),
 (4409, 0.0),
 (4408, 0.09567297464698797),
 (4407, 0.0),
 (4406, 0.06917144638660747),
 (4405, 0.26490647141300877),
 (4404, 0.0),
 (4403, 0.16222142113076254),
 (4402, 0.05564148840746572),
 (4401, 0.04415107856883479),
 (4400, 0.07254762501100116),
 (4399, 0.06917144638660747),
 (4398, 0.04335549847620599),
 (4397, 0.04188539082916955),
 (4396, 0.0),
 (4395, 0.0),
 (4394, 0.0),
 (4393, 0.0),
 (4392, 0.12166606584807188),
 (4391, 0.0),
 (4390, 0.06917144638660747),
 (4389, 0.06362847629757777),
 (4388, 0.0),
 (4387, 0.0),
 (4386, 0.0),
 (4385, 0.0),
 (4384, 0.08830215713766958),
 (4383, 0.05647824947249049),
 (4382, 0.059234887775909226),
 (4381, 0.0),
 (4380, 0.0),
 (4379, 0.0),
 (4378, 0.0),
 (4377, 0.10012523486435176),
 (4376, 0.0),
 (4375, 0.07647191129018724),
 (4374, 0.0),
 (4373, 0.0),
 (4372, 0.09782319760890368),
 (4371, 0.03877833671647406),
 (4370, 0.0),
 (4369, 0.10012523486435176),
 (4368, 0.07254762501100116),
 (4367, 0.0),
 (4366, 0.0),
 (4365, 0.1025978352085154),
 (4364, 0.0),
 (4363, 0.0),
 (4362, 0.07647191129018724),
 (4361, 0.0),
 (4360, 0.0),
 (4359, 0.042601432284230495),
 (4358, 0.09637388493048532),
 (4357, 0.10814761408717502),
 (4356, 0.0),
 (4355, 0.13245323570650439),
 (4354, 0.0),
 (4353, 0.14509525002200233),
 (4352, 0.0),
 (4351, 0.11128297681493143),
 (4350, 0.0),
 (4349, 0.06362847629757777),
 (4348, 0.24333213169614376),
 (4347, 0.0),
 (4346, 0.0),
 (4345, 0.0),
 (4344, 0.0),
 (4343, 0.1873171623163388),
 (4342, 0.0),
 (4341, 0.17770466332772766),
 (4340, 0.0),
 (4339, 0.11470786693528087),
 (4338, 0.0),
 (4337, 0.0),
 (4336, 0.29346959282671103),
 (4335, 0.03934447376823168),
 (4334, 0.0),
 (4333, 0.07647191129018724),
 (4332, 0.06622661785325219),
 (4331, 0.15789473684210523),
 (4330, 0.11164843913471803),
 (4329, 0.10814761408717502),
 (4328, 0.0),
 (4327, 0.0),
 (4326, 0.07165743639000186),
 (4325, 0.09567297464698797),
 (4324, 0.047836487323493986),
 (4323, 0.059234887775909226),
 (4322, 0.0),
 (4321, 0.0),
 (4320, 0.11470786693528087),
 (4319, 0.06302534916632545),
 (4318, 0.0),
 (4317, 0.03993615319154359),
 (4316, 0.16222142113076254),
 (4315, 0.0),
 (4314, 0.03539961627023943),
 (4313, 0.057353933467640436),
 (4312, 0.11470786693528087),
 (4311, 0.0),
 (4310, 0.10012523486435176),
 (4309, 0.0),
 (4308, 0.0),
 (4307, 0.0),
 (4306, 0.0),
 (4305, 0.042601432284230495),
 (4304, 0.0),
 (4303, 0.0),
 (4302, 0.0),
 (4301, 0.0),
 (4300, 0.07647191129018724),
 (4299, 0.0468292905790847),
 (4298, 0.0),
 (4297, 0.05263157894736841),
 (4296, 0.0),
 (4295, 0.0),
 (4294, 0.0),
 (4293, 0.0936585811581694),
 (4292, 0.0),
 (4291, 0.0),
 (4290, 0.11846977555181845),
 (4289, 0.0),
 (4288, 0.04891159880445184),
 (4287, 0.03823595564509362),
 (4286, 0.05407380704358751),
 (4285, 0.0),
 (4284, 0.04588314677411235),
 (4283, 0.047836487323493986),
 (4282, 0.06622661785325219),
 (4281, 0.08671099695241198),
 (4280, 0.04335549847620599),
 (4279, 0.13834289277321493),
 (4278, 0.0),
 (4277, 0.0),
 (4276, 0.0),
 (4275, 0.0),
 (4274, 0.0),
 (4273, 0.0),
 (4272, 0.0),
 (4271, 0.0),
 (4270, 0.0),
 (4269, 0.0),
 (4268, 0.13006649542861798),
 (4267, 0.03458572319330373),
 (4266, 0.0),
 (4265, 0.08671099695241198),
 (4264, 0.04335549847620599),
 (4263, 0.0468292905790847),
 (4262, 0.0),
 (4261, 0.07254762501100116),
 (4260, 0.041204282171516456),
 (4259, 0.07254762501100116),
 (4258, 0.0),
 (4257, 0.0),
 (4256, 0.15789473684210523),
 (4255, 0.0),
 (4254, 0.0),
 (4253, 0.0),
 (4252, 0.021873931962990353),
 (4251, 0.0),
 (4250, 0.04588314677411235),
 (4249, 0.03539961627023943),
 (4248, 0.06362847629757777),
 (4247, 0.0),
 (4246, 0.08671099695241198),
 (4245, 0.0),
 (4244, 0.06765100914917382),
 (4243, 0.0),
 (4242, 0.0),
 (4241, 0.0),
 (4240, 0.042601432284230495),
 (4239, 0.0),
 (4238, 0.09567297464698797),
 (4237, 0.08111071056538126),
 (4236, 0.08111071056538126),
 (4235, 0.029867384554474945),
 (4234, 0.10526315789473682),
 (4233, 0.0),
 (4232, 0.0),
 (4231, 0.0),
 (4230, 0.22941573387056174),
 (4229, 0.0),
 (4228, 0.0512989176042577),
 (4227, 0.047836487323493986),
 (4226, 0.0),
 (4225, 0.08285522649991611),
 (4224, 0.0),
 (4223, 0.0),
 (4222, 0.0),
 (4221, 0.0),
 (4220, 0.06362847629757777),
 (4219, 0.0),
 (4218, 0.0512989176042577),
 (4217, 0.03673591791853225),
 (4216, 0.13834289277321493),
 (4215, 0.0468292905790847),
 (4214, 0.05006261743217588),
 (4213, 0.08671099695241198),
 (4212, 0.0),
 (4211, 0.04891159880445184),
 (4210, 0.0),
 (4209, 0.04335549847620599),
 (4208, 0.0),
 (4207, 0.04891159880445184),
 (4206, 0.06362847629757777),
 (4205, 0.14350946197048195),
 (4204, 0.06362847629757777),
 (4203, 0.18394180184548975),
 (4202, 0.06362847629757777),
 (4201, 0.0),
 (4200, 0.0),
 (4199, 0.0),
 (4198, 0.15294382258037448),
 (4197, 0.0),
 (4196, 0.12262786789699316),
 (4195, 0.06131393394849658),
 (4194, 0.04499212706658475),
 (4193, 0.04588314677411235),
 (4192, 0.38177085778546666),
 (4191, 0.0),
 (4190, 0.0),
 (4189, 0.0),
 (4188, 0.0),
 (4187, 0.04499212706658475),
 (4186, 0.0),
 (4185, 0.0),
 (4184, 0.057353933467640436),
 (4183, 0.0),
 (4182, 0.0),
 (4181, 0.0837707816583391),
 (4180, 0.13245323570650436),
 (4179, 0.03673591791853225),
 (4178, 0.03877833671647406),
 (4177, 0.0),
 (4176, 0.03993615319154359),
 (4175, 0.0),
 (4174, 0.0),
 (4173, 0.0),
 (4172, 0.0),
 (4171, 0.0),
 (4170, 0.0),
 (4169, 0.06692744814102546),
 (4168, 0.042601432284230495),
 (4167, 0.0),
 (4166, 0.11846977555181845),
 (4165, 0.16222142113076252),
 (4164, 0.0),
 (4163, 0.04415107856883479),
 (4162, 0.0),
 (4161, 0.06131393394849658),
 (4160, 0.1025978352085154),
 (4159, 0.0),
 (4158, 0.0),
 (4157, 0.0),
 (4156, 0.047836487323493986),
 (4155, 0.0),
 (4154, 0.07647191129018724),
 (4153, 0.0),
 (4152, 0.0),
 (4151, 0.07509392614826382),
 (4150, 0.0),
 (4149, 0.0),
 (4148, 0.0734718358370645),
 (4147, 0.0),
 (4146, 0.07647191129018724),
 (4145, 0.0),
 (4144, 0.0),
 (4143, 0.08111071056538126),
 (4142, 0.0),
 (4141, 0.05006261743217588),
 (4140, 0.0),
 (4139, 0.059234887775909226),
 (4138, 0.08671099695241198),
 (4137, 0.059234887775909226),
 (4136, 0.0),
 (4135, 0.15789473684210523),
 (4134, 0.08111071056538126),
 (4133, 0.0),
 (4132, 0.05407380704358751),
 (4131, 0.059234887775909226),
 (4130, 0.07647191129018724),
 (4129, 0.027226638505866502),
 (4128, 0.0),
 (4127, 0.0512989176042577),
 (4126, 0.0),
 (4125, 0.10814761408717502),
 (4124, 0.042601432284230495),
 (4123, 0.12780429685269148),
 (4122, 0.0),
 (4121, 0.0),
 (4120, 0.05407380704358751),
 (4119, 0.06362847629757777),
 (4118, 0.0),
 (4117, 0.0899842541331695),
 (4116, 0.048636038308579745),
 (4115, 0.057353933467640436),
 (4114, 0.08111071056538126),
 (4113, 0.06131393394849658),
 (4112, 0.13834289277321493),
 (4111, 0.0),
 (4110, 0.05263157894736841),
 (4109, 0.06131393394849658),
 (4108, 0.0),
 (4107, 0.05564148840746572),
 (4106, 0.0),
 (4105, 0.03346372407051273),
 (4104, 0.0),
 (4103, 0.061868822488974594),
 (4102, 0.0),
 (4101, 0.0),
 (4100, 0.10748615458500278),
 (4099, 0.13834289277321493),
 (4098, 0.0),
 (4097, 0.22941573387056174),
 (4096, 0.0),
 (4095, 0.0),
 (4094, 0.06362847629757777),
 (4093, 0.0),
 (4092, 0.0),
 (4091, 0.05263157894736841),
 (4090, 0.12262786789699316),
 (4089, 0.0),
 (4088, 0.0),
 (4087, 0.1025978352085154),
 (4086, 0.0),
 (4085, 0.06131393394849658),
 (4084, 0.0917662935482247),
 (4083, 0.1538967528127731),
 (4082, 0.0),
 (4081, 0.0),
 (4080, 0.08240856434303291),
 (4079, 0.2445579940222592),
 (4078, 0.06917144638660747),
 (4077, 0.10039117221153819),
 (4076, 0.06917144638660747),
 (4075, 0.08111071056538126),
 (4074, 0.0),
 (4073, 0.0),
 (4072, 0.07254762501100116),
 (4071, 0.0),
 (4070, 0.0),
 (4069, 0.04891159880445184),
 (4068, 0.07755667343294811),
 (4067, 0.03771571432023571),
 (4066, 0.05407380704358751),
 (4065, 0.047836487323493986),
 (4064, 0.0),
 (4063, 0.059234887775909226),
 (4062, 0.1025978352085154),
 (4061, 0.12262786789699316),
 (4060, 0.0),
 (4059, 0.04415107856883479),
 (4058, 0.0),
 (4057, 0.0),
 (4056, 0.0),
 (4055, 0.08520286456846099),
 (4054, 0.0),
 (4053, 0.0),
 (4052, 0.08111071056538126),
 (4051, 0.0),
 (4050, 0.0),
 (4049, 0.0),
 (4048, 0.3712129349338476),
 (4047, 0.03877833671647406),
 (4046, 0.10814761408717502),
 (4045, 0.15018785229652765),
 (4044, 0.06362847629757777),
 (4043, 0.05263157894736841),
 (4042, 0.0),
 (4041, 0.0),
 (4040, 0.0),
 (4039, 0.05263157894736841),
 (4038, 0.06622661785325219),
 (4037, 0.0),
 (4036, 0.1025978352085154),
 (4035, 0.0),
 (4034, 0.0),
 (4033, 0.0),
 (4032, 0.0),
 (4031, 0.0),
 (4030, 0.06362847629757777),
 (4029, 0.059234887775909226),
 (4028, 0.021775177815467107),
 (4027, 0.0),
 (4026, 0.08671099695241198),
 (4025, 0.06131393394849658),
 (4024, 0.028903665650803993),
 (4023, 0.05564148840746572),
 (4022, 0.033113308926626096),
 (4021, 0.05407380704358751),
 (4020, 0.0),
 (4019, 0.21052631578947364),
 (4018, 0.2075143391598224),
 (4017, 0.04891159880445184),
 (4016, 0.0),
 (4015, 0.0),
 (4014, 0.0),
 (4013, 0.041204282171516456),
 (4012, 0.0917662935482247),
 (4011, 0.15294382258037448),
 (4010, 0.2545139051903111),
 (4009, 0.05006261743217588),
 (4008, 0.08671099695241198),
 (4007, 0.0),
 (4006, 0.06131393394849658),
 (4005, 0.0),
 (4004, 0.0),
 (4003, 0.0324442842261525),
 (4002, 0.0899842541331695),
 (4001, 0.0),
 (4000, 0.16222142113076252),
 (3999, 0.31578947368421045),
 (3998, 0.0),
 (3997, 0.0734718358370645),
 (3996, 0.06622661785325219),
 (3995, 0.10814761408717502),
 (3994, 0.1025978352085154),
 (3993, 0.03993615319154359),
 (3992, 0.08111071056538126),
 (3991, 0.06362847629757777),
 (3990, 0.041204282171516456),
 (3989, 0.06917144638660747),
 (3988, 0.1025978352085154),
 (3987, 0.04415107856883479),
 (3986, 0.0),
 (3985, 0.0),
 (3984, 0.0),
 (3983, 0.05006261743217588),
 (3982, 0.21629522817435004),
 (3981, 0.0),
 (3980, 0.0),
 (3979, 0.057353933467640436),
 (3978, 0.13834289277321493),
 (3977, 0.0),
 (3976, 0.0),
 (3975, 0.0),
 (3974, 0.0),
 (3973, 0.0),
 (3972, 0.06362847629757777),
 (3971, 0.06622661785325219),
 (3970, 0.0),
 (3969, 0.0),
 (3968, 0.0512989176042577),
 (3967, 0.0),
 (3966, 0.0),
 (3965, 0.0),
 (3964, 0.0),
 (3963, 0.033113308926626096),
 (3962, 0.07647191129018724),
 (3961, 0.02761840883330537),
 (3960, 0.0),
 (3959, 0.0),
 (3958, 0.0),
 (3957, 0.0),
 (3956, 0.0512989176042577),
 (3955, 0.06622661785325219),
 (3954, 0.057353933467640436),
 (3953, 0.0512989176042577),
 (3952, 0.0),
 (3951, 0.027420424855354085),
 (3950, 0.0468292905790847),
 (3949, 0.06917144638660747),
 (3948, 0.07165743639000186),
 (3947, 0.05647824947249049),
 (3946, 0.06131393394849658),
 (3945, 0.0),
 (3944, 0.0),
 (3943, 0.0),
 (3942, 0.0),
 (3941, 0.07254762501100116),
 (3940, 0.0),
 (3939, 0.0),
 (3938, 0.07254762501100116),
 (3937, 0.04499212706658475),
 (3936, 0.0),
 (3935, 0.17342199390482396),
 (3934, 0.06131393394849658),
 (3933, 0.0),
 (3932, 0.047836487323493986),
 (3931, 0.11846977555181845),
 (3930, 0.0468292905790847),
 (3929, 0.11470786693528087),
 (3928, 0.03065696697424829),
 (3927, 0.0),
 (3926, 0.15018785229652765),
 (3925, 0.04499212706658475),
 (3924, 0.06362847629757777),
 (3923, 0.0936585811581694),
 (3922, 0.0),
 (3921, 0.06362847629757777),
 (3920, 0.0),
 (3919, 0.11470786693528087),
 (3918, 0.06917144638660747),
 (3917, 0.05263157894736841),
 (3916, 0.06131393394849658),
 (3915, 0.0),
 (3914, 0.08671099695241198),

In [54]:
#sorting based on the similarity and pick only 5 most similar movie. leaving the similarity of movie with itself.
sorted(list(enumerate(distances)),reverse=True,key=lambda x : x[1])[1:6]

[(507, 0.5619514869490164),
 (151, 0.4866642633922876),
 (1216, 0.4640161686673095),
 (1204, 0.45056355688958294),
 (322, 0.44539933408304444)]

In [60]:
#how to use iloc
print(new_df.iloc[322].title)

The Fifth Element

In [61]:
def recommend(movie):
    movie_index=new_df[new_df['title']==movie].index[0]
    distances=similarity[movie_index]
    movies=sorted(list(enumerate(distances)),reverse=True,key=lambda x : x[1])[1:6]
    for i in movies:
        print(new_df.iloc[i[0]].title) #i[0] has movie index.

In [62]:
recommend("Avatar")

Independence Day
Beowulf
Aliens vs Predator: Requiem
Predators
The Fifth Element

In [63]:
import pickle
#python pickle module is used for serializing and deserializing python object structures.
#the process to convert any kind of python objects(list,dict...) into byte streams (0 and 1) is called serialization or pickling
#the reverse process is unpickling.

In [ ]:
#dump is used for serializing
#load is used for deserializing.

In [64]:
pickle.dump(new_df,open("movies.pkl","wb"))

In [65]:
pickle.dump(similarity,open("similarity.pkl","wb"))